# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-16 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='备份号')),
                ('status', models.SmallIntegerField(default=0, verbose_name='备份状态')),
                ('filename', models.CharField(max_length=64, verbose_name='备份目录名称')),
            ],
            options={
                'db_table': 'tb_backup_info',
                'verbose_name_plural': '备份基本信息',
                'verbose_name': '备份基本信息',
            },
        ),
        migrations.CreateModel(
            name='DatabaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=64, verbose_name='用户数据库名称')),
                ('host_ip', models.CharField(max_length=64, verbose_name='服务器IP')),
                ('dbuser', models.CharField(max_length=64, verbose_name='数据库用户')),
                ('dbpassword', models.CharField(max_length=64, verbose_name='数据库用户密码')),
                ('dbport', models.CharField(max_length=64, verbose_name='数据库端口')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'db_table': 'tb_database_info',
                'verbose_name_plural': '用户数据库基本信息',
                'verbose_name': '用户数据库基本信息',
            },
        ),
    ]
