# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-11 02:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='备份号')),
                ('host_ip', models.CharField(max_length=64, verbose_name='服务器IP')),
                ('dbuser', models.CharField(max_length=64, verbose_name='数据库用户')),
                ('dbpassword', models.CharField(max_length=64, verbose_name='数据库用户密码')),
                ('dbport', models.CharField(max_length=64, verbose_name='数据库端口')),
                ('status', models.SmallIntegerField(default=0, verbose_name='备份状态')),
                ('filename', models.CharField(max_length=64, verbose_name='备份目录名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '备份基本信息',
                'db_table': 'tb_backup_info',
                'verbose_name_plural': '备份基本信息',
            },
        ),
    ]
