# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-16 00:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='数据库用户'),
        ),
        migrations.AddField(
            model_name='backupinfo',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contents.DatabaseInfo', verbose_name='数据库编号'),
        ),
        migrations.AddField(
            model_name='backupinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='订单用户'),
        ),
    ]
